[package]
name = "simplified-blockchain-merkle-tree-zk-snark-zk-rollup-a-playful-approach"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
